application: recommendy
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /(.*\.(html|ico|gif|png|jpg|js|css|less|ico|woff|tff|svg|eot))
  static_files: static/\1
  upload: static/(.*\.(html|ico|gif|png|jpg|js|css|less|ico|woff|tff|svg|eot))

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
